### ISSUE TITLE
Unsafe Conditions

### ISSUE THREAD

**Issue by bucks0042** [switux/AstroWeatherStation#128]
Please consider to implement following unsafe condition :

Unsafe if :

- Cloudly for more as x seconds (To be defined in user interface)
- Overcast -> Immediately
- Rain -> Immediately
- wind : more than x seconds (TBDF in user interface) if wind is more as x m/s, immediately in case of wind more as y m/s

Revert to safe :

- immediately for cloudy to clear
- after x seconds for overcast
- after x seconds for Rain
- immediately for wind "x" after x seconds for wind "y"

**Comment by switux** [comment]
![Image](https://github.com/switux/AstroWeatherStation/assets/71386598/b5bce69b-6acd-4893-a2c9-f7fb688c3c09)

**Comment by switux** [comment]
It kind of works but there are some corner cases to be sorted out. I suggest we agree on a (simple) state machine asap.
